In [ ]:
import pandas as pd
import numpy as np

### Series : Another data type in Python its represented as a table with only 1 coumn and auto assignes rowids

In [ ]:
series1 = pd.Series([1,2,3,4,5])
print(series1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
series1.values

array([1, 2, 3, 4, 5])

In [ ]:
k = list(series1.index)
k ,series1.index

([0, 1, 2, 3, 4], RangeIndex(start=0, stop=5, step=1))

In [ ]:
series2 = pd.Series([1,2,3,4,5], index = ["One","Two","Three","Four","Five"])
series2

One      1
Two      2
Three    3
Four     4
Five     5
dtype: int64

In [ ]:
series2[2]

3

In [ ]:
series2['Three']

3

In [ ]:
series2 * 4

One       4
Two       8
Three    12
Four     16
Five     20
dtype: int64

In [ ]:
# Subset the entire series 

series2[series2>3]

Four    4
Five    5
dtype: int64

In [ ]:
series2 = series2 + 5
series2

One       6
Two       7
Three     8
Four      9
Five     10
dtype: int64

In [ ]:
series2[series2 > 7]

Three     8
Four      9
Five     10
dtype: int64

### DataFrame

In [ ]:
data_frame = pd.DataFrame({
    "Col1": [1,2,3],
    "Col2":[10,20,30],
    "Col3":["a","b","c"]
})

data_frame

   Col1  Col2 Col3
0     1    10    a
1     2    20    b
2     3    30    c

In [ ]:
data_frame.loc[2] # Picks Row index

Col1     3
Col2    30
Col3     c
Name: 2, dtype: object

In [ ]:
data_frame['Col3'] # Picks Column index

0    a
1    b
2    c
Name: Col3, dtype: object

In [ ]:
data_frame['Col4'] = ["a1","b1","c1"]

data_frame

   Col1  Col2 Col3 Col4
0     1    10    a   a1
1     2    20    b   b1
2     3    30    c   c1

In [ ]:
#df.loc[len(df.index)] = ['Amy', 89, 93] 

data_frame.loc[len(data_frame.index)] = ['Amy', 89, 93, 100]

  Col1  Col2 Col3 Col4
0    1    10    a   a1
1    2    20    b   b1
2    3    30    c   c1
3  Amy    89   93  100
4  Amy    89   93  100
5  Amy    89   93  100

In [ ]:
data_frame.drop([4,5],axis=0, inplace=True)

data_frame

  Col1  Col2 Col3 Col4
0    1    10    a   a1
1    2    20    b   b1
2    3    30    c   c1
3  Amy    89   93  100

In [ ]:
data_frame['Col5']='NaN'

data_frame

  Col1  Col2 Col3 Col4 Col5
0    1    10    a   a1  NaN
1    2    20    b   b1  NaN
2    3    30    c   c1  NaN
3  Amy    89   93  100  NaN

In [ ]:
del data_frame['Col5']

data_frame

  Col1  Col2 Col3 Col4
0    1    10    a   a1
1    2    20    b   b1
2    3    30    c   c1
3  Amy    89   93  100

In [ ]:
data_frame.insert(loc=1, column='dummy Col', value = ['d1','d2','d3','d4'])

data_frame

  Col1 dummy Col  Col2 Col3 Col4
0    1        d1    10    a   a1
1    2        d2    20    b   b1
2    3        d3    30    c   c1
3  Amy        d4    89   93  100

In [ ]:
del data_frame['dummy Col']

In [ ]:
data_frame.loc[:,'Col2']

0    10
1    20
2    30
3    89
Name: Col2, dtype: int64

In [ ]:
# pick a particular value based on ro and column index
print(data_frame)
data_frame.iloc[2,3]

  Col1  Col2 Col3 Col4
0    1    10    a   a1
1    2    20    b   b1
2    3    30    c   c1
3  Amy    89   93  100

'c1'

In [ ]:
#selecting first 2 rows
data_frame[:2]

  Col1  Col2 Col3 Col4
0    1    10    a   a1
1    2    20    b   b1

In [ ]:
data_frame.iloc[:2,:2] #Getting 0 to 2 row nadn column

  Col1  Col2
0    1    10
1    2    20

In [ ]:
data_frame.iloc[:,[1,3]]

   Col2 Col4
0    10   a1
1    20   b1
2    30   c1
3    89  100

In [ ]:
# data_frame.loc[len(data_frame.index)] = [4, 89, 'd', 'd1']
# data_frame.loc[len(data_frame.index)] = [5, 81, 'e', 'e1']
# data_frame.loc[len(data_frame.index)] = [6, 84, 'f', 'f1']
# data_frame.loc[len(data_frame.index)] = [7, 85, 'g', 'g1']
# data_frame.loc[len(data_frame.index)] = [8, 98, 'h', 'h1']

# data_frame.drop([3,4,5,6,7,8,9,10,11,12,13],axis=0, inplace=True)

data_frame

  Col1  Col2 Col3 Col4
0    1    10    a   a1
1    2    20    b   b1
2    3    30    c   c1
3    4    89    d   d1
4    5    81    e   e1
5    6    84    f   f1
6    7    85    g   g1
7    8    98    h   h1

In [ ]:
new_data_frame = data_frame.iloc[2:5,:]
print(new_data_frame)

  Col1  Col2 Col3 Col4
2    3    30    c   c1
3    4    89    d   d1
4    5    81    e   e1

In [ ]:
new_data_frame.reset_index(drop=True,inplace=True)

new_data_frame

  Col1  Col2 Col3 Col4
0    3    30    c   c1
1    4    89    d   d1
2    5    81    e   e1

In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv("autodata.csv")

df.head()

df1 = df.set_index(["make","num-of-cylinders","body-style"])

df1

                                         peak-rpm curb-weight wheel-base  \
make        num-of-cylinders body-style
alfa-romero four             convertible     5000        2548       88.6
                             convertible     5000        2823       88.6
            six              hatchback       5500        2337          ?
audi        four             sedan              ?        2824       99.8
            five             sedan           5500        2507       99.4
...                                           ...         ...        ...
volkswagen  four             sedan           6000        2385       97.3
                             sedan           6000        2500       97.3
?           four             sedan           4800        2385       97.3
volvo       four             sedan           4800        2410      104.3
                             wagon           4800        2385      104.3

                                          length engine-type horsepower  \
make        num-of-cylinders body-style
alfa-romero four             convertible   168.8        dohc        111
                             convertible   168.8        dohc        111
            six              hatchback     171.2        ohcv        154
audi        four             sedan         176.6         ohc        102
            five             sedan         176.6         ohc        115
...                                          ...         ...        ...
volkswagen  four             sedan         171.7         ohc         85
                             sedan         171.7         ohc      13213
?           four             sedan         171.7         ohc        100
volvo       four             sedan         188.8         ohc        114
                             wagon         188.8         ohc        114

                                         city-mpg  price
make        num-of-cylinders body-style
alfa-romero four             convertible       21  13495
                             convertible       21  16500
            six              hatchback         19  16500
audi        four             sedan             24  13950
            five             sedan             18  17450
...                                           ...    ...
volkswagen  four             sedan             27   7975
                             sedan             37   7995
?           four             sedan             26   9995
volvo       four             sedan             23  12940
                             wagon             23  13415

[61 rows x 8 columns]

In [6]:
arr = np.arange(20).reshape(-1,5)
df_num = pd.DataFrame(arr, columns=list('12345'))
df_num

    1   2   3   4   5
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [12]:
L1 = ['a', 'b', 'c', 'd']
L2 = ['e', 'f', 'g']

L1+L2

L1

['a', 'b', 'c', 'd']